server:
  port: 8088
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ljl.pojo

#数据库连接池
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC

